#!/bin/sh
case $1 in
	# like weather script
	1)
		if [[ ! -e "/tmp/packages" ]]; then
			notify-send "Please synchronize package databases first"
		else
			st -i -g 125x30 -e "nvim" "/tmp/packages"
		fi
		;;
	2)
		ps -e | grep clash >/dev/null
		[[ $? -ne 0 ]] && ep
		notify-send "Synchronizing package databases..."
		yay -Sy > /dev/null && yay -Qu > /tmp/packages
		sigdwmblocks 9;;
	3) "st" -e "nvim" "$0";;
	4)
		notify-send "Synchronizing package databases..."
		st -i -g 125x30 -e "yay" "-Syu"
		yay -Qu > /tmp/packages
		sigdwmblocks 9;;
	5) notify-send "delete /tmp/packages" && rm /tmp/packages;;
esac
[ "$1" != "" ] && exit
if [[ ! -e "/tmp/packages" ]]; then
	# notify-send "Synchronizing package databases..."
	# yay -Sy > /dev/null
	# yay -Qu > /tmp/packages
	package=`yay -Qu | wc -l`
else
	package=`cat /tmp/packages | wc -l`
fi
# notify-send -t 2000 "Synchronizing package databases..."
# yay -Sy > /dev/null
# yay -Qu > /tmp/packages
[[ $package -eq 0 ]] && echo 📦$package && notify-send "You are up to date" && exit 0
notify-send "📦$package are upgradable"
echo 📦$package
